# Generated by Django 4.2.23 on 2025-08-02 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_is_anonymous_alter_user_is_authenticated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='address_id',
            new_name='addresses',
        ),
    ]
